# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-10 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krish', '0003_addpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpost',
            name='project_image1',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
