# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-11 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krish', '0005_auto_20190910_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpost',
            name='Death',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='addpost',
            name='Education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='addpost',
            name='Guru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='addpost',
            name='Spouse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
