# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-11 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krish', '0006_auto_20190911_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpost',
            name='Philosopy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='addpost',
            name='Wife',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
