# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-12 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krish', '0008_auto_20190911_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpage',
            name='excerpt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
