# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-18 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krish', '0012_latestnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpage',
            name='project_image2',
            field=models.FileField(blank=True, null=True, upload_to='mission_pics'),
        ),
        migrations.AddField(
            model_name='addpage',
            name='ramakrishna',
            field=models.CharField(choices=[('About us', 'About us'), ('Academics', 'Academics'), ('Admissions', 'Admissions'), ('Studentcorner', 'Studentcorner')], max_length=50, null=True),
        ),
    ]
