# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-20 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krish', '0013_auto_20190918_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpage',
            name='ramakrishna',
            field=models.CharField(choices=[('About us', 'About us'), ('Academics', 'Academics'), ('Admissions', 'Admissions'), ('Studentcorner', 'Studentcorner'), ('Careers', 'careers'), ('infrastructure', 'infrastructure')], max_length=50, null=True),
        ),
    ]
