# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-24 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('krish', '0015_donations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donations',
            old_name='description',
            new_name='excerpt',
        ),
        migrations.AddField(
            model_name='donations',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='donations',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='donations',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donations',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donations',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='donations',
            name='project_image2',
            field=models.FileField(blank=True, null=True, upload_to='mission_pics'),
        ),
        migrations.AddField(
            model_name='donations',
            name='slug',
            field=models.SlugField(blank=True, max_length=900, null=True),
        ),
    ]
